/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manual grouping for better control
  tutorialSidebar: [
    'intro', // Keep your main intro
    {
      type: 'category',
      label: '👨‍💻 User Guide',
      items: [{type: 'autogenerated', dirName: 'user-guide'}],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: '⚙️ Admin Guide',
      items: [{type: 'autogenerated', dirName: 'admin-guide'}],
      collapsible: true,
      collapsed: true, // Keep admin stuff closed by default
    },
    // Keep your API/Drift demos separate
    {
      type: 'category',
      label: '⚡ Demos',
      items: [{type: 'autogenerated', dirName: 'api'}], 
    },
  ],
};

export default sidebars;